[build]
target = "x86_64-operating_system.json"
target-dir = "target"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
panic-abort-tests = true

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
